<project>
	<modelVersion>4.0.0</modelVersion>

	<groupId>career-mentor</groupId>
	<artifactId>oop</artifactId>
	<version>1.0.0</version>
	<packaging>jar</packaging>

	<properties>
		<maven.compiler.release>26</maven.compiler.release>
	</properties>

	<build>
		<sourceDirectory>src</sourceDirectory>

		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>1.18.46</version>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
			<dependency>
					<groupId>org.projectlombok</groupId>
					<artifactId>lombok</artifactId>
					<version>1.18.46</version>
					<scope>provided</scope>
			</dependency>
	</dependencies>
</project>